### ISSUE TITLE
Signal handling meta-issue

### ISSUE THREAD

**Issue by pvdrz** [memorysafety/sudo-rs#521]
This issue tracks if `sudo-rs` behaves the same as ogsudo when receiving certain signals:

- [ ] SIGALRM: Tracked by #448 
- [ ] SIGCHLD: This is indirectly tested by the fact that we handle SIGCHLD by waiting for child processes but we shouldn't misbehave if someone sends us a fake SIGCHLD.
- [ ] SIGCONT
- [ ] SIGHUP
- [ ] SIGINT
- [ ] SIGKILL: It is not possible to handle this signal but we shouldn't leave child processes hanging around.
- [ ] SIGQUIT
- [ ] SIGSTOP: It is not possible to handle this signal
- [ ] SIGTSTP: Tracked by #325 
- [ ] SIGTERM
- [ ] SIGTTIN
- [ ] SIGTTOU
- [ ] SIGUSR1
- [ ] SIGUSR2
- [ ] SIGWINCH
