### ISSUE TITLE
Don't poll file descriptors if the callbacks for them are no-ops

### ISSUE THREAD

**Issue by pvdrz** [memorysafety/sudo-rs#522]
In some cases it is not necessary to poll file descriptors because their callbacks won't do anything even if they are ready. There are several instances of this:
- [x] Polling the backchannel for writing even though there are no messages queued to be sent over it (fixed via #599).
- [ ] Polling the user's terminal or the leader side of the pty for read or write even though the pipe internal buffer is empty or full (fixed via #611).
- [x] Polling the user's terminal or the leader side of the pty while sudo is suspended (fixed via #595)

Solving this requires to add an API to temporarily avoid polling a specific file descriptor.
